export type ComponentMeta = {
  name: string
  title: string
  description: string
  solid: boolean
}

export const components: ComponentMeta[] = [
  {
    name: "button",
    title: "Button",
    description: "Displays a button or a component that looks like a button.",
    solid: true,
  },
  {
    name: "button-group",
    title: "Button Group",
    description: "Displays grouped controls.",
    solid: true,
  },
  {
    name: "card",
    title: "Card",
    description: "Displays a card with header, content, and footer.",
    solid: true,
  },
  {
    name: "input",
    title: "Input",
    description: "Displays a form input field.",
    solid: true,
  },
  {
    name: "input-group",
    title: "Input Group",
    description: "Displays input controls with addons.",
    solid: true,
  },
  {
    name: "table",
    title: "Table",
    description: "Displays tabular data.",
    solid: true,
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "Displays a set of layered sections.",
    solid: true,
  },
  {
    name: "badge",
    title: "Badge",
    description: "Displays a badge or status label.",
    solid: true,
  },
  {
    name: "alert",
    title: "Alert",
    description: "Displays contextual status information.",
    solid: true,
  },
  {
    name: "aspect-ratio",
    title: "Aspect Ratio",
    description: "Displays content within a fixed ratio.",
    solid: true,
  },
  {
    name: "accordion",
    title: "Accordion",
    description: "Displays collapsible content sections.",
    solid: true,
  },
  {
    name: "checkbox",
    title: "Checkbox",
    description: "Displays a checkbox control.",
    solid: true,
  },
  {
    name: "radio-group",
    title: "Radio Group",
    description: "Displays a set of radio controls.",
    solid: true,
  },
  {
    name: "select",
    title: "Select",
    description: "Displays a select control.",
    solid: true,
  },
  {
    name: "switch",
    title: "Switch",
    description: "Displays an on/off control.",
    solid: true,
  },
  {
    name: "textarea",
    title: "Textarea",
    description: "Displays a multiline text field.",
    solid: true,
  },
  {
    name: "progress",
    title: "Progress",
    description: "Displays task progress.",
    solid: true,
  },
  {
    name: "slider",
    title: "Slider",
    description: "Displays a range control.",
    solid: true,
  },
  {
    name: "toggle",
    title: "Toggle",
    description: "Displays a toggle control.",
    solid: true,
  },
  {
    name: "toggle-group",
    title: "Toggle Group",
    description: "Displays grouped toggle controls.",
    solid: true,
  },
  {
    name: "avatar",
    title: "Avatar",
    description: "Displays a user or resource identity image.",
    solid: true,
  },
  {
    name: "breadcrumb",
    title: "Breadcrumb",
    description: "Displays the current navigation path.",
    solid: true,
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Displays pagination controls.",
    solid: true,
  },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "Displays a loading placeholder.",
    solid: true,
  },
  {
    name: "spinner",
    title: "Spinner",
    description: "Displays loading progress.",
    solid: true,
  },
  {
    name: "separator",
    title: "Separator",
    description: "Displays a visual divider.",
    solid: true,
  },
  {
    name: "carousel",
    title: "Carousel",
    description: "Displays a carousel region.",
    solid: true,
  },
  {
    name: "calendar",
    title: "Calendar",
    description: "Displays a date picker calendar.",
    solid: true,
  },
  {
    name: "chart",
    title: "Chart",
    description: "Displays data visualizations.",
    solid: true,
  },
  {
    name: "command",
    title: "Command",
    description: "Displays a command menu.",
    solid: true,
  },
  {
    name: "combobox",
    title: "Combobox",
    description: "Displays a searchable select control.",
    solid: true,
  },
  {
    name: "collapsible",
    title: "Collapsible",
    description: "Displays expandable content.",
    solid: true,
  },
  {
    name: "context-menu",
    title: "Context Menu",
    description: "Displays contextual actions.",
    solid: true,
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "Displays modal content.",
    solid: true,
  },
  {
    name: "direction",
    title: "Direction",
    description: "Provides text direction context.",
    solid: true,
  },
  {
    name: "alert-dialog",
    title: "Alert Dialog",
    description: "Displays a confirmation dialog.",
    solid: true,
  },
  {
    name: "dropdown-menu",
    title: "Dropdown Menu",
    description: "Displays menu actions.",
    solid: true,
  },
  {
    name: "popover",
    title: "Popover",
    description: "Displays floating contextual content.",
    solid: true,
  },
  {
    name: "hover-card",
    title: "Hover Card",
    description: "Displays hover-triggered contextual content.",
    solid: true,
  },
  {
    name: "tooltip",
    title: "Tooltip",
    description: "Displays short contextual help.",
    solid: true,
  },
  {
    name: "sheet",
    title: "Sheet",
    description: "Displays side-panel content.",
    solid: true,
  },
  {
    name: "drawer",
    title: "Drawer",
    description: "Displays drawer content.",
    solid: true,
  },
  {
    name: "empty",
    title: "Empty",
    description: "Displays an empty state.",
    solid: true,
  },
  {
    name: "field",
    title: "Field",
    description: "Displays field layout primitives.",
    solid: true,
  },
  {
    name: "form",
    title: "Form",
    description: "Displays form field composition.",
    solid: true,
  },
  {
    name: "input-otp",
    title: "Input OTP",
    description: "Displays segmented input slots.",
    solid: true,
  },
  {
    name: "label",
    title: "Label",
    description: "Displays a field label.",
    solid: true,
  },
  {
    name: "item",
    title: "Item",
    description: "Displays structured list content.",
    solid: true,
  },
  {
    name: "kbd",
    title: "Kbd",
    description: "Displays keyboard input.",
    solid: true,
  },
  {
    name: "scroll-area",
    title: "Scroll Area",
    description: "Displays custom scrollable content.",
    solid: true,
  },
  {
    name: "resizable",
    title: "Resizable",
    description: "Displays resizable panel layouts.",
    solid: true,
  },
  {
    name: "menubar",
    title: "Menubar",
    description: "Displays application menu actions.",
    solid: true,
  },
  {
    name: "navigation-menu",
    title: "Navigation Menu",
    description: "Displays navigation menu content.",
    solid: true,
  },
  {
    name: "native-select",
    title: "Native Select",
    description: "Displays a native select control.",
    solid: true,
  },
  {
    name: "sidebar",
    title: "Sidebar",
    description: "Displays an application sidebar shell.",
    solid: true,
  },
  {
    name: "sonner",
    title: "Sonner",
    description: "Displays toast notifications.",
    solid: true,
  },
]
