import { createContext, createSignal, splitProps, useContext, Show, type JSX } from "solid-js"
import { XIcon } from "@/registry/solid/lib/icons"
import { cn } from "@/registry/solid/lib/utils"
import { Button, buttonVariants } from "@/registry/solid/ui/button"
type Ctx = { open: () => boolean; setOpen: (open: boolean) => void }
const DialogContext = createContext<Ctx>()
function AlertDialog(props: JSX.HTMLAttributes<HTMLDivElement> & { open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void }) { const [l,r]=splitProps(props,["open","defaultOpen","onOpenChange","children"]); const [open,setOpenSignal]=createSignal(!!l.defaultOpen); const ctx={ open:()=>l.open ?? open(), setOpen:(v:boolean)=>{setOpenSignal(v); l.onOpenChange?.(v)} }; return <DialogContext.Provider value={ctx}><div data-slot="alert-dialog" {...r}>{l.children}</div></DialogContext.Provider> }
function AlertDialogTrigger(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { const ctx=useContext(DialogContext); return <button type="button" data-slot="alert-dialog-trigger" onClick={() => ctx?.setOpen(true)} {...props}/> }
function AlertDialogPortal(props: JSX.HTMLAttributes<HTMLDivElement>) { return <>{props.children}</> }
function AlertDialogOverlay(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="alert-dialog-overlay" class={cn("fixed inset-0 z-50 bg-black/50 data-[state=open]:animate-in data-[state=closed]:animate-out",l.class)} {...r}/> }
function AlertDialogContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class","children"]); const ctx=useContext(DialogContext); return <Show when={ctx?.open()}><AlertDialogOverlay/><div role="dialog" data-slot="alert-dialog-content" class={cn("fixed top-[50%] left-[50%] z-50 grid w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] gap-4 rounded-lg border bg-background p-6 shadow-lg sm:max-w-lg",l.class)} {...r}>{l.children}<AlertDialogClose class="absolute top-4 right-4 rounded-xs opacity-70 transition-opacity hover:opacity-100 focus:ring-2 focus:ring-ring focus:outline-hidden disabled:pointer-events-none"><XIcon class="size-4"/><span class="sr-only">Close</span></AlertDialogClose></div></Show> }
function AlertDialogHeader(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="alert-dialog-header" class={cn("flex flex-col gap-2 text-center sm:text-left",l.class)} {...r}/> }
function AlertDialogFooter(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="alert-dialog-footer" class={cn("flex flex-col-reverse gap-2 sm:flex-row sm:justify-end",l.class)} {...r}/> }
function AlertDialogTitle(props: JSX.HTMLAttributes<HTMLHeadingElement>) { const [l,r]=splitProps(props,["class"]); return <h2 data-slot="alert-dialog-title" class={cn("text-lg leading-none font-semibold",l.class)} {...r}/> }
function AlertDialogDescription(props: JSX.HTMLAttributes<HTMLParagraphElement>) { const [l,r]=splitProps(props,["class"]); return <p data-slot="alert-dialog-description" class={cn("text-sm text-muted-foreground",l.class)} {...r}/> }
function AlertDialogClose(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { const ctx=useContext(DialogContext); return <button type="button" data-slot="alert-dialog-close" onClick={() => ctx?.setOpen(false)} {...props}/> }
function AlertDialogAction(props: Parameters<typeof Button>[0]) { return <Button data-slot="alert-dialog-action" {...props}/> }
function AlertDialogCancel(props: Parameters<typeof Button>[0]) { return <Button data-slot="alert-dialog-cancel" variant="outline" {...props}/> }
export { AlertDialog, AlertDialogPortal, AlertDialogOverlay, AlertDialogTrigger, AlertDialogClose, AlertDialogContent, AlertDialogHeader, AlertDialogFooter, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel }
