import { splitProps, type JSX } from "solid-js"
import { ChevronRightIcon, MoreHorizontalIcon } from "lucide-solid"
import { cn } from "@/registry/solid/lib/utils"
function Breadcrumb(props: JSX.HTMLAttributes<HTMLElement>) { const [l,r]=splitProps(props,["class"]); return <nav aria-label="breadcrumb" data-slot="breadcrumb" class={cn(l.class)} {...r}/> }
function BreadcrumbList(props: JSX.OlHTMLAttributes<HTMLOListElement>) { const [l,r]=splitProps(props,["class"]); return <ol data-slot="breadcrumb-list" class={cn("flex flex-wrap items-center gap-1.5 text-sm break-words text-muted-foreground sm:gap-2",l.class)} {...r}/> }
function BreadcrumbItem(props: JSX.LiHTMLAttributes<HTMLLIElement>) { const [l,r]=splitProps(props,["class"]); return <li data-slot="breadcrumb-item" class={cn("inline-flex items-center gap-1.5",l.class)} {...r}/> }
function BreadcrumbLink(props: JSX.AnchorHTMLAttributes<HTMLAnchorElement>) { const [l,r]=splitProps(props,["class"]); return <a data-slot="breadcrumb-link" class={cn("rounded-md px-1 transition-colors hover:text-foreground focus-visible:ring-[3px] focus-visible:ring-ring/35 focus-visible:outline-none",l.class)} {...r}/> }
function BreadcrumbPage(props: JSX.HTMLAttributes<HTMLSpanElement>) { const [l,r]=splitProps(props,["class"]); return <span data-slot="breadcrumb-page" role="link" aria-disabled="true" aria-current="page" class={cn("font-medium text-foreground",l.class)} {...r}/> }
function BreadcrumbSeparator(props: JSX.LiHTMLAttributes<HTMLLIElement>) { const [l,r]=splitProps(props,["class","children"]); return <li data-slot="breadcrumb-separator" role="presentation" aria-hidden="true" class={cn("text-muted-foreground/70 [&>svg]:size-3.5",l.class)} {...r}>{l.children || <ChevronRightIcon />}</li> }
function BreadcrumbEllipsis(props: JSX.HTMLAttributes<HTMLSpanElement>) { const [l,r]=splitProps(props,["class"]); return <span data-slot="breadcrumb-ellipsis" role="presentation" aria-hidden="true" class={cn("flex size-8 items-center justify-center rounded-md hover:bg-accent",l.class)} {...r}><MoreHorizontalIcon class="size-4"/><span class="sr-only">More</span></span> }
export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis }
