import { splitProps, type JSX } from "solid-js"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/registry/solid/lib/utils"
import { Separator } from "@/registry/solid/ui/separator"
const buttonGroupVariants = cva("flex w-fit items-stretch has-[>[data-slot=button-group]]:gap-2 [&>*:focus-visible]:relative [&>*:focus-visible]:z-10 [&>*:hover]:relative [&>*:hover]:z-10 [&>[data-slot=select-trigger]:not([class*='w-'])]:w-fit [&>input]:flex-1", { variants: { orientation: { horizontal: "[&>*:first-child]:rounded-l-full [&>*:last-child]:rounded-r-full [&>*:not(:first-child)]:-ml-0.5 [&>*:not(:first-child)]:rounded-l-none [&>*:not(:last-child)]:rounded-r-none", vertical: "flex-col [&>*:first-child]:rounded-t-full [&>*:last-child]:rounded-b-full [&>*:not(:first-child)]:-mt-0.5 [&>*:not(:first-child)]:rounded-t-none [&>*:not(:last-child)]:rounded-b-none" } }, defaultVariants: { orientation: "horizontal" } })
function ButtonGroup(props: JSX.HTMLAttributes<HTMLDivElement> & VariantProps<typeof buttonGroupVariants>) { const [l,r]=splitProps(props,["class","orientation"]); return <div role="group" data-slot="button-group" data-orientation={l.orientation || "horizontal"} class={cn(buttonGroupVariants({orientation:l.orientation}),l.class)} {...r}/> }
function ButtonGroupText(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="button-group-text" class={cn("flex h-10 items-center gap-2 border border-border bg-card px-3 text-sm font-medium text-muted-foreground [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4",l.class)} {...r}/> }
function ButtonGroupSeparator(props: JSX.HTMLAttributes<HTMLDivElement> & { orientation?: "horizontal" | "vertical" }) { const [l,r]=splitProps(props,["class","orientation"]); return <Separator data-slot="button-group-separator" orientation={l.orientation || "vertical"} class={cn("relative m-0! self-stretch bg-border data-vertical:h-auto",l.class)} {...r}/> }
export { ButtonGroup, ButtonGroupSeparator, ButtonGroupText, buttonGroupVariants }
