import { splitProps, type JSX } from "solid-js"
import { CheckIcon, ChevronRightIcon, CircleIcon } from "lucide-solid"
import { cn } from "@/registry/solid/lib/utils"
function ContextMenu(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="context-menu" class={cn("relative inline-block",l.class)} {...r}/> }
function ContextMenuPortal(props: JSX.HTMLAttributes<HTMLDivElement>) { return <>{props.children}</> }
function ContextMenuTrigger(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { return <button type="button" data-slot="context-menu-trigger" {...props}/> }
function ContextMenuContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="context-menu-content" class={cn("z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md",l.class)} {...r}/> }
function ContextMenuGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="context-menu-group" {...props}/> }
function ContextMenuLabel(props: JSX.HTMLAttributes<HTMLDivElement> & { inset?: boolean }) { const [l,r]=splitProps(props,["class","inset"]); return <div data-slot="context-menu-label" data-inset={l.inset} class={cn("px-2.5 py-1.5 text-xs font-semibold text-muted-foreground data-inset:pl-8",l.class)} {...r}/> }
function ContextMenuItem(props: JSX.HTMLAttributes<HTMLDivElement> & { inset?: boolean; variant?: "default" | "destructive" }) { const [l,r]=splitProps(props,["class","inset","variant"]); return <div role="menuitem" data-slot="context-menu-item" data-inset={l.inset} data-variant={l.variant||"default"} class={cn("relative flex h-8 cursor-default items-center gap-2 rounded-md px-2.5 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8 data-[variant=destructive]:text-destructive data-[variant=destructive]:hover:bg-destructive/10 data-[variant=destructive]:hover:text-destructive data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground data-[variant=destructive]:*:[svg]:text-destructive!",l.class)} {...r}/> }
function ContextMenuSub(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="context-menu-sub" {...props}/> }
function ContextMenuSubTrigger(props: JSX.HTMLAttributes<HTMLDivElement> & { inset?: boolean }) { const [l,r]=splitProps(props,["class","inset","children"]); return <div data-slot="context-menu-sub-trigger" data-inset={l.inset} class={cn("flex h-8 cursor-default items-center rounded-md px-2.5 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8",l.class)} {...r}>{l.children}<ChevronRightIcon class="ml-auto"/></div> }
function ContextMenuSubContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <ContextMenuContent data-slot="context-menu-sub-content" class={cn("shadow-md",l.class)} {...r}/> }
function ContextMenuCheckboxItem(props: JSX.HTMLAttributes<HTMLDivElement> & { checked?: boolean; inset?: boolean }) { const [l,r]=splitProps(props,["class","checked","inset","children"]); return <div role="menuitemcheckbox" aria-checked={l.checked} data-slot="context-menu-checkbox-item" data-inset={l.inset} class={cn("relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8",l.class)} {...r}><span class="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">{l.checked && <CheckIcon class="size-4"/>}</span>{l.children}</div> }
function ContextMenuRadioGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="context-menu-radio-group" {...props}/> }
function ContextMenuRadioItem(props: JSX.HTMLAttributes<HTMLDivElement> & { checked?: boolean; inset?: boolean }) { const [l,r]=splitProps(props,["class","checked","inset","children"]); return <div role="menuitemradio" aria-checked={l.checked} data-slot="context-menu-radio-item" data-inset={l.inset} class={cn("relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8",l.class)} {...r}><span class="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">{l.checked && <CircleIcon class="size-2 fill-current"/>}</span>{l.children}</div> }
function ContextMenuSeparator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="context-menu-separator" class={cn("-mx-1 my-1 h-px bg-border",l.class)} {...r}/> }
function ContextMenuShortcut(props: JSX.HTMLAttributes<HTMLSpanElement>) { const [l,r]=splitProps(props,["class"]); return <span data-slot="context-menu-shortcut" class={cn("ml-auto text-xs tracking-widest text-muted-foreground",l.class)} {...r}/> }
export { ContextMenu, ContextMenuPortal, ContextMenuTrigger, ContextMenuContent, ContextMenuGroup, ContextMenuLabel, ContextMenuItem, ContextMenuShortcut, ContextMenuCheckboxItem, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSub, ContextMenuSubTrigger, ContextMenuSubContent, ContextMenuSeparator }
