import { splitProps, type JSX } from "solid-js"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/registry/solid/lib/utils"
function Empty(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="empty" class={cn("flex min-w-0 flex-1 flex-col items-center justify-center gap-6 rounded-lg border border-dashed p-6 text-center text-balance md:p-12",l.class)} {...r}/> }
function EmptyHeader(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="empty-header" class={cn("flex max-w-sm flex-col items-center gap-2 text-center",l.class)} {...r}/> }
const emptyMediaVariants = cva("mb-2 flex shrink-0 items-center justify-center [&_svg]:pointer-events-none [&_svg]:shrink-0", { variants: { variant: { default: "bg-transparent", icon: "flex size-10 shrink-0 items-center justify-center rounded-lg border border-primary/20 bg-primary/10 text-primary [&_svg:not([class*='size-'])]:size-5" } }, defaultVariants: { variant: "default" } })
function EmptyMedia(props: JSX.HTMLAttributes<HTMLDivElement> & VariantProps<typeof emptyMediaVariants>) { const [l,r]=splitProps(props,["class","variant"]); return <div data-slot="empty-icon" data-variant={l.variant||"default"} class={cn(emptyMediaVariants({variant:l.variant}),l.class)} {...r}/> }
function EmptyTitle(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="empty-title" class={cn("text-lg font-semibold tracking-tight",l.class)} {...r}/> }
function EmptyDescription(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="empty-description" class={cn("text-sm/relaxed text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",l.class)} {...r}/> }
function EmptyContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="empty-content" class={cn("flex w-full max-w-sm min-w-0 flex-col items-center gap-4 text-sm text-balance",l.class)} {...r}/> }
export { Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyContent, EmptyMedia }
