import { splitProps, type JSX } from "solid-js"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/registry/solid/lib/utils"
import { Separator } from "@/registry/solid/ui/separator"
function ItemGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div role="list" data-slot="item-group" class={cn("group/item-group flex w-full flex-col",l.class)} {...r}/> }
function ItemSeparator(props: Parameters<typeof Separator>[0]) { const [l,r]=splitProps(props,["class"]); return <Separator data-slot="item-separator" orientation="horizontal" class={cn("my-0",l.class)} {...r}/> }
const itemVariants = cva("group/item flex w-full flex-wrap items-center rounded-md border border-transparent text-sm transition-colors duration-100 outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/35 [a]:transition-colors [a]:hover:bg-primary/10", { variants: { variant: { default: "border-transparent", outline: "border-border", muted: "border-transparent bg-muted/50" }, size: { default: "gap-2.5 px-3 py-2", sm: "gap-2 px-2.5 py-1.5 text-xs", xs: "gap-2 px-2 py-1 text-xs in-data-[slot=dropdown-menu-content]:p-0" } }, defaultVariants: { variant: "default", size: "default" } })
function Item(props: JSX.HTMLAttributes<HTMLDivElement> & VariantProps<typeof itemVariants>) { const [l,r]=splitProps(props,["class","variant","size"]); return <div data-slot="item" data-variant={l.variant||"default"} data-size={l.size||"default"} class={cn(itemVariants({variant:l.variant,size:l.size}),l.class)} {...r}/> }
const itemMediaVariants = cva("flex shrink-0 items-center justify-center gap-2 group-has-[[data-slot=item-description]]/item:translate-y-0.5 group-has-[[data-slot=item-description]]/item:self-start [&_svg]:pointer-events-none", { variants: { variant: { default: "bg-transparent", icon: "[&_svg:not([class*='size-'])]:size-4", image: "size-10 overflow-hidden rounded-sm group-data-[size=sm]/item:size-8 group-data-[size=xs]/item:size-6 [&_img]:size-full [&_img]:object-cover" } }, defaultVariants: { variant: "default" } })
function ItemMedia(props: JSX.HTMLAttributes<HTMLDivElement> & VariantProps<typeof itemMediaVariants>) { const [l,r]=splitProps(props,["class","variant"]); return <div data-slot="item-media" data-variant={l.variant||"default"} class={cn(itemMediaVariants({variant:l.variant}),l.class)} {...r}/> }
function ItemContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="item-content" class={cn("flex flex-1 flex-col gap-1 [&+[data-slot=item-content]]:flex-none",l.class)} {...r}/> }
function ItemTitle(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="item-title" class={cn("flex w-fit items-center gap-2 text-sm leading-snug font-semibold",l.class)} {...r}/> }
function ItemDescription(props: JSX.HTMLAttributes<HTMLParagraphElement>) { const [l,r]=splitProps(props,["class"]); return <p data-slot="item-description" class={cn("line-clamp-2 text-sm leading-normal font-normal text-balance text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",l.class)} {...r}/> }
function ItemActions(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="item-actions" class={cn("flex items-center gap-2",l.class)} {...r}/> }
function ItemHeader(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="item-header" class={cn("flex basis-full items-center justify-between gap-2",l.class)} {...r}/> }
function ItemFooter(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="item-footer" class={cn("flex basis-full items-center justify-between gap-2",l.class)} {...r}/> }
export { Item, ItemMedia, ItemContent, ItemActions, ItemGroup, ItemSeparator, ItemTitle, ItemDescription, ItemHeader, ItemFooter }
