import { splitProps, type JSX } from "solid-js"
import { CheckIcon, ChevronRightIcon, CircleIcon } from "lucide-solid"
import { cn } from "@/registry/solid/lib/utils"
function Menubar(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="menubar" class={cn("flex h-9 items-center gap-1 rounded-md border border-border bg-card p-1",l.class)} {...r}/> }
function MenubarPortal(props: JSX.HTMLAttributes<HTMLDivElement>) { return <>{props.children}</> }
function MenubarTrigger(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { const [l,r]=splitProps(props,["class"]); return <button type="button" data-slot="menubar-trigger" class={cn("flex h-7 items-center rounded-md px-2.5 text-sm font-medium outline-hidden select-none focus:bg-primary/10 focus:text-foreground aria-expanded:bg-primary/10 aria-expanded:text-foreground",l.class)} {...r}/> }
function MenubarContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="menubar-content" class={cn("z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md",l.class)} {...r}/> }
function MenubarGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="menubar-group" {...props}/> }
function MenubarLabel(props: JSX.HTMLAttributes<HTMLDivElement> & { inset?: boolean }) { const [l,r]=splitProps(props,["class","inset"]); return <div data-slot="menubar-label" data-inset={l.inset} class={cn("px-2.5 py-1.5 text-xs font-semibold text-muted-foreground data-inset:pl-8",l.class)} {...r}/> }
function MenubarItem(props: JSX.HTMLAttributes<HTMLDivElement> & { inset?: boolean; variant?: "default" | "destructive" }) { const [l,r]=splitProps(props,["class","inset","variant"]); return <div role="menuitem" data-slot="menubar-item" data-inset={l.inset} data-variant={l.variant||"default"} class={cn("relative flex h-8 cursor-default items-center gap-2 rounded-md px-2.5 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8 data-[variant=destructive]:text-destructive data-[variant=destructive]:hover:bg-destructive/10 data-[variant=destructive]:hover:text-destructive data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground data-[variant=destructive]:*:[svg]:text-destructive!",l.class)} {...r}/> }
function MenubarSub(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="menubar-sub" {...props}/> }
function MenubarSubTrigger(props: JSX.HTMLAttributes<HTMLDivElement> & { inset?: boolean }) { const [l,r]=splitProps(props,["class","inset","children"]); return <div data-slot="menubar-sub-trigger" data-inset={l.inset} class={cn("flex h-8 cursor-default items-center rounded-md px-2.5 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8",l.class)} {...r}>{l.children}<ChevronRightIcon class="ml-auto"/></div> }
function MenubarSubContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <MenubarContent data-slot="menubar-sub-content" class={cn("shadow-md",l.class)} {...r}/> }
function MenubarCheckboxItem(props: JSX.HTMLAttributes<HTMLDivElement> & { checked?: boolean; inset?: boolean }) { const [l,r]=splitProps(props,["class","checked","inset","children"]); return <div role="menuitemcheckbox" aria-checked={l.checked} data-slot="menubar-checkbox-item" data-inset={l.inset} class={cn("relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8",l.class)} {...r}><span class="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">{l.checked && <CheckIcon class="size-4"/>}</span>{l.children}</div> }
function MenubarRadioGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="menubar-radio-group" {...props}/> }
function MenubarRadioItem(props: JSX.HTMLAttributes<HTMLDivElement> & { checked?: boolean; inset?: boolean }) { const [l,r]=splitProps(props,["class","checked","inset","children"]); return <div role="menuitemradio" aria-checked={l.checked} data-slot="menubar-radio-item" data-inset={l.inset} class={cn("relative flex h-8 cursor-default items-center gap-2 rounded-md pr-2.5 pl-8 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-inset:pl-8",l.class)} {...r}><span class="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">{l.checked && <CircleIcon class="size-2 fill-current"/>}</span>{l.children}</div> }
function MenubarSeparator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="menubar-separator" class={cn("-mx-1 my-1 h-px bg-border",l.class)} {...r}/> }
function MenubarShortcut(props: JSX.HTMLAttributes<HTMLSpanElement>) { const [l,r]=splitProps(props,["class"]); return <span data-slot="menubar-shortcut" class={cn("ml-auto text-xs tracking-widest text-muted-foreground",l.class)} {...r}/> }
export { Menubar, MenubarPortal, MenubarTrigger, MenubarContent, MenubarGroup, MenubarLabel, MenubarItem, MenubarShortcut, MenubarCheckboxItem, MenubarRadioGroup, MenubarRadioItem, MenubarSub, MenubarSubTrigger, MenubarSubContent, MenubarSeparator }
