import { splitProps, type JSX } from "solid-js"
import { ChevronDownIcon } from "lucide-solid"
import { cva } from "class-variance-authority"
import { cn } from "@/registry/solid/lib/utils"
function NavigationMenu(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <nav data-slot="navigation-menu" class={cn("group/navigation-menu relative flex max-w-max flex-1 items-center justify-center",l.class)} {...r}/> }
function NavigationMenuList(props: JSX.HTMLAttributes<HTMLUListElement>) { const [l,r]=splitProps(props,["class"]); return <ul data-slot="navigation-menu-list" class={cn("group flex flex-1 list-none items-center justify-center gap-1",l.class)} {...r}/> }
function NavigationMenuItem(props: JSX.LiHTMLAttributes<HTMLLIElement>) { const [l,r]=splitProps(props,["class"]); return <li data-slot="navigation-menu-item" class={cn("relative",l.class)} {...r}/> }
const navigationMenuTriggerStyle = cva("group/navigation-menu-trigger inline-flex h-9 w-max items-center justify-center rounded-full border border-transparent bg-card px-4 py-2 text-sm font-medium transition-[background-color,border-color,color,box-shadow] outline-none hover:border-border hover:bg-primary/10 hover:text-foreground focus:bg-primary/10 focus:text-foreground focus-visible:ring-[3px] focus-visible:ring-ring/35 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 data-open:border-primary data-open:bg-primary/10 data-open:text-primary")
function NavigationMenuTrigger(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { const [l,r]=splitProps(props,["class","children"]); return <button type="button" data-slot="navigation-menu-trigger" class={cn(navigationMenuTriggerStyle(),"group",l.class)} {...r}>{l.children} <ChevronDownIcon class="relative top-[1px] ml-1 size-3 transition duration-300" aria-hidden="true"/></button> }
function NavigationMenuContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="navigation-menu-content" class={cn("w-auto p-2 pr-2.5",l.class)} {...r}/> }
function NavigationMenuLink(props: JSX.AnchorHTMLAttributes<HTMLAnchorElement>) { const [l,r]=splitProps(props,["class"]); return <a data-slot="navigation-menu-link" class={cn("flex flex-col gap-1 rounded-md p-2.5 text-sm transition-[background-color,color,box-shadow] outline-none hover:bg-primary/10 hover:text-foreground focus:bg-primary/10 focus:text-foreground focus-visible:ring-[3px] focus-visible:ring-ring/35 focus-visible:outline-none data-active:bg-primary/10 data-active:text-primary [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground",l.class)} {...r}/> }
function NavigationMenuIndicator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="navigation-menu-indicator" class={cn("top-full z-1 flex h-1.5 items-end justify-center overflow-hidden",l.class)} {...r}><div class="relative top-[60%] h-2 w-2 rotate-45 rounded-tl-sm bg-border shadow-md"/></div> }
function NavigationMenuPositioner(props: JSX.HTMLAttributes<HTMLDivElement>) { return <div data-slot="navigation-menu-positioner" {...props}/> }
export { NavigationMenu, NavigationMenuContent, NavigationMenuIndicator, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, navigationMenuTriggerStyle, NavigationMenuPositioner }
