import { createContext, createSignal, splitProps, useContext, Show, type JSX } from "solid-js"
import { CheckIcon, ChevronDownIcon, ChevronUpIcon } from "@/registry/solid/lib/icons"
import { cn } from "@/registry/solid/lib/utils"
type Ctx={open:()=>boolean;setOpen:(v:boolean)=>void;value:()=>string|undefined;setValue:(v:string)=>void}; const C=createContext<Ctx>()
function Select(props: JSX.HTMLAttributes<HTMLDivElement> & { defaultValue?: string; value?: string; onValueChange?: (value:string)=>void }) { const [l,r]=splitProps(props,["children","defaultValue","value","onValueChange"]); const [open,setOpen]=createSignal(false); const [value,setValueSignal]=createSignal(l.defaultValue); const ctx={open,setOpen,value:()=>l.value ?? value(),setValue:(v:string)=>{setValueSignal(v);l.onValueChange?.(v);setOpen(false)}}; return <C.Provider value={ctx}><div data-slot="select" class="relative inline-block" {...r}>{l.children}</div></C.Provider> }
function SelectGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="select-group" class={cn("scroll-my-1 p-1",l.class)} {...r}/> }
function SelectValue(props: JSX.HTMLAttributes<HTMLSpanElement> & { placeholder?: string }) { const [l,r]=splitProps(props,["class","placeholder","children"]); const c=useContext(C); return <span data-slot="select-value" class={cn("flex flex-1 text-left",l.class)} {...r}>{l.children || c?.value() || l.placeholder}</span> }
function SelectTrigger(props: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { size?: "sm"|"default" }) { const [l,r]=splitProps(props,["class","size","children"]); const c=useContext(C); const size=l.size||"default"; return <button type="button" data-slot="select-trigger" data-size={size} class={cn("flex w-fit items-center justify-between gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm whitespace-nowrap transition-[border-color,box-shadow] outline-none hover:border-input focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/35 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 data-placeholder:text-muted-foreground data-[size=default]:h-10 data-[size=sm]:h-8 dark:bg-input/30 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground",l.class)} onClick={()=>c?.setOpen(!c.open())} {...r}>{l.children}<ChevronDownIcon class="size-4 opacity-50"/></button> }
function SelectContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); const c=useContext(C); return <Show when={c?.open()}><div data-slot="select-content" class={cn("absolute z-50 mt-1 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md",l.class)} {...r}/></Show> }
function SelectLabel(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="select-label" class={cn("px-2.5 py-1.5 text-xs font-semibold text-muted-foreground",l.class)} {...r}/> }
function SelectItem(props: JSX.HTMLAttributes<HTMLDivElement> & { value: string }) { const [l,r]=splitProps(props,["class","value","children"]); const c=useContext(C); const active=()=>c?.value()===l.value; return <div role="option" data-slot="select-item" data-active={active()?"":undefined} class={cn("relative flex h-8 w-full cursor-default items-center gap-2 rounded-md pr-8 pl-2.5 text-sm outline-hidden select-none hover:bg-primary/10 hover:text-foreground data-active:bg-primary/10 data-active:text-foreground",l.class)} onClick={()=>c?.setValue(l.value)} {...r}><span class="flex flex-1 shrink-0 items-center gap-2 whitespace-nowrap">{l.children}</span>{active() && <span class="pointer-events-none absolute right-2 flex size-3.5 items-center justify-center"><CheckIcon class="size-4"/></span>}</div> }
function SelectSeparator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="select-separator" class={cn("pointer-events-none -mx-1 my-1 h-px bg-border",l.class)} {...r}/> }
function SelectScrollUpButton(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="select-scroll-up-button" class={cn("top-0 z-10 flex w-full cursor-default items-center justify-center bg-popover py-1 [&_svg:not([class*='size-'])]:size-4",l.class)} {...r}><ChevronUpIcon/></div> }
function SelectScrollDownButton(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="select-scroll-down-button" class={cn("bottom-0 z-10 flex w-full cursor-default items-center justify-center bg-popover py-1 [&_svg:not([class*='size-'])]:size-4",l.class)} {...r}><ChevronDownIcon/></div> }
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue }
