import { createContext, createSignal, splitProps, useContext, type JSX } from "solid-js"
import { PanelLeftIcon } from "lucide-solid"
import { cn } from "@/registry/solid/lib/utils"
import { Button } from "@/registry/solid/ui/button"
const SIDEBAR_WIDTH = "16rem"
const SIDEBAR_WIDTH_ICON = "3rem"
const SidebarContext = createContext({ open: () => true, setOpen: (_: boolean) => {} })
function SidebarProvider(props: JSX.HTMLAttributes<HTMLDivElement> & { defaultOpen?: boolean }) { const [l,r]=splitProps(props,["class","defaultOpen","children","style"]); const [open,setOpen]=createSignal(l.defaultOpen ?? true); return <SidebarContext.Provider value={{open,setOpen}}><div data-slot="sidebar-wrapper" style={{"--sidebar-width":SIDEBAR_WIDTH,"--sidebar-width-icon":SIDEBAR_WIDTH_ICON,...(l.style as JSX.CSSProperties)}} class={cn("group/sidebar-wrapper flex min-h-svh w-full",l.class)} {...r}>{l.children}</div></SidebarContext.Provider> }
function useSidebar() { return useContext(SidebarContext) }
function Sidebar(props: JSX.HTMLAttributes<HTMLDivElement> & { collapsible?: "offcanvas" | "icon" | "none" }) { const [l,r]=splitProps(props,["class","collapsible"]); return <aside data-slot="sidebar" class={cn(l.collapsible === "none" ? "flex h-full w-(--sidebar-width) flex-col bg-sidebar text-sidebar-foreground" : "w-64 shrink-0 border-r border-sidebar-border bg-sidebar text-sidebar-foreground",l.class)} {...r}/> }
function SidebarTrigger(props: Parameters<typeof Button>[0]) { const [l,r]=splitProps(props,["class"]); const s=useSidebar(); return <Button data-slot="sidebar-trigger" variant="ghost" size="icon" class={cn("size-7",l.class)} onClick={()=>s.setOpen(!s.open())} {...r}><PanelLeftIcon/><span class="sr-only">Toggle Sidebar</span></Button> }
function SidebarRail(props: JSX.HTMLAttributes<HTMLButtonElement>) { return <button data-slot="sidebar-rail" {...props}/> }
function SidebarInset(props: JSX.HTMLAttributes<HTMLElement>) { const [l,r]=splitProps(props,["class"]); return <main data-slot="sidebar-inset" class={cn("relative flex w-full flex-1 flex-col bg-background",l.class)} {...r}/> }
function SidebarInput(props: JSX.InputHTMLAttributes<HTMLInputElement>) { const [l,r]=splitProps(props,["class"]); return <input data-slot="sidebar-input" class={cn("h-8 w-full rounded-md border bg-background px-2 text-sm",l.class)} {...r}/> }
function SidebarHeader(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-header" class={cn("flex flex-col gap-2 p-2",l.class)} {...r}/> }
function SidebarFooter(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-footer" class={cn("flex flex-col gap-2 p-2",l.class)} {...r}/> }
function SidebarSeparator(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-separator" class={cn("mx-2 h-px bg-sidebar-border",l.class)} {...r}/> }
function SidebarContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-content" class={cn("flex min-h-0 flex-1 flex-col gap-2 overflow-auto",l.class)} {...r}/> }
function SidebarGroup(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-group" class={cn("relative flex w-full min-w-0 flex-col p-2",l.class)} {...r}/> }
function SidebarGroupLabel(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-group-label" class={cn("flex h-8 shrink-0 items-center rounded-md px-2 text-xs font-semibold text-sidebar-foreground/70",l.class)} {...r}/> }
function SidebarGroupAction(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { const [l,r]=splitProps(props,["class"]); return <button data-slot="sidebar-group-action" class={cn("absolute top-3.5 right-3 flex aspect-square w-5 items-center justify-center rounded-md hover:bg-sidebar-accent",l.class)} {...r}/> }
function SidebarGroupContent(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-group-content" class={cn("w-full text-sm",l.class)} {...r}/> }
function SidebarMenu(props: JSX.HTMLAttributes<HTMLUListElement>) { const [l,r]=splitProps(props,["class"]); return <ul data-slot="sidebar-menu" class={cn("flex w-full min-w-0 flex-col gap-1",l.class)} {...r}/> }
function SidebarMenuItem(props: JSX.LiHTMLAttributes<HTMLLIElement>) { const [l,r]=splitProps(props,["class"]); return <li data-slot="sidebar-menu-item" class={cn("group/menu-item relative",l.class)} {...r}/> }
function SidebarMenuButton(props: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { isActive?: boolean }) { const [l,r]=splitProps(props,["class","isActive"]); return <button data-slot="sidebar-menu-button" data-active={l.isActive} class={cn("flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left text-sm outline-hidden transition-[background-color,color] hover:bg-sidebar-primary/10 hover:text-sidebar-foreground active:bg-sidebar-primary/10 active:text-sidebar-primary data-[active=true]:bg-sidebar-primary/10 data-[active=true]:font-semibold data-[active=true]:text-sidebar-primary",l.class)} {...r}/> }
function SidebarMenuAction(props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) { const [l,r]=splitProps(props,["class"]); return <button data-slot="sidebar-menu-action" class={cn("absolute top-1.5 right-1 flex aspect-square w-5 items-center justify-center rounded-md hover:bg-sidebar-accent",l.class)} {...r}/> }
function SidebarMenuBadge(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-menu-badge" class={cn("absolute right-1 flex h-5 min-w-5 items-center justify-center rounded-md px-1 text-xs",l.class)} {...r}/> }
function SidebarMenuSkeleton(props: JSX.HTMLAttributes<HTMLDivElement>) { const [l,r]=splitProps(props,["class"]); return <div data-slot="sidebar-menu-skeleton" class={cn("h-8 rounded-md bg-sidebar-accent",l.class)} {...r}/> }
function SidebarMenuSub(props: JSX.HTMLAttributes<HTMLUListElement>) { const [l,r]=splitProps(props,["class"]); return <ul data-slot="sidebar-menu-sub" class={cn("mx-3.5 flex min-w-0 translate-x-px flex-col gap-1 border-l border-sidebar-border px-2.5 py-0.5",l.class)} {...r}/> }
function SidebarMenuSubItem(props: JSX.LiHTMLAttributes<HTMLLIElement>) { return <li data-slot="sidebar-menu-sub-item" {...props}/> }
function SidebarMenuSubButton(props: JSX.AnchorHTMLAttributes<HTMLAnchorElement> & { isActive?: boolean }) { const [l,r]=splitProps(props,["class","isActive"]); return <a data-slot="sidebar-menu-sub-button" data-active={l.isActive} class={cn("flex h-7 min-w-0 items-center gap-2 overflow-hidden rounded-md px-2 text-sidebar-foreground outline-hidden hover:bg-sidebar-accent hover:text-sidebar-accent-foreground data-[active=true]:bg-sidebar-accent data-[active=true]:text-sidebar-accent-foreground",l.class)} {...r}/> }
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar }
