import { createContext, createSignal, splitProps, useContext, type JSX } from "solid-js"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/registry/solid/lib/utils"
type Ctx = { value: () => string | undefined; setValue: (value: string) => void }
const TabsContext = createContext<Ctx>()
function Tabs(props: JSX.HTMLAttributes<HTMLDivElement> & { value?: string; defaultValue?: string; onValueChange?: (value: string) => void; orientation?: "horizontal" | "vertical" }) { const [l,r]=splitProps(props,["class","value","defaultValue","onValueChange","orientation","children"]); const [value,setValueSignal]=createSignal(l.defaultValue); const orientation=l.orientation||"horizontal"; const ctx={ value:()=>l.value ?? value(), setValue:(v:string)=>{setValueSignal(v); l.onValueChange?.(v)} }; return <TabsContext.Provider value={ctx}><div data-slot="tabs" data-orientation={orientation} data-horizontal={orientation==="horizontal"?"":undefined} data-vertical={orientation==="vertical"?"":undefined} class={cn("group/tabs flex gap-2 data-horizontal:flex-col",l.class)} {...r}>{l.children}</div></TabsContext.Provider> }
const tabsListVariants = cva("group/tabs-list inline-flex items-center text-muted-foreground group-data-vertical/tabs:h-fit group-data-vertical/tabs:flex-col group-data-vertical/tabs:items-stretch", { variants: { variant: { default: "gap-5 group-data-horizontal/tabs:h-10 group-data-horizontal/tabs:w-full group-data-horizontal/tabs:justify-start group-data-horizontal/tabs:border-b group-data-vertical/tabs:border-r", line: "gap-5 group-data-horizontal/tabs:h-10 group-data-horizontal/tabs:w-full group-data-horizontal/tabs:justify-start group-data-horizontal/tabs:border-b group-data-vertical/tabs:border-r", segmented: "w-fit gap-0 rounded-full border border-border bg-card p-0.5 group-data-horizontal/tabs:h-10" } }, defaultVariants: { variant: "default" } })
function TabsList(props: JSX.HTMLAttributes<HTMLDivElement> & VariantProps<typeof tabsListVariants>) { const [l,r]=splitProps(props,["class","variant"]); return <div role="tablist" data-slot="tabs-list" data-variant={l.variant||"default"} class={cn(tabsListVariants({variant:l.variant}),l.class)} {...r}/> }
function TabsTrigger(props: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { value: string }) { const [l,r]=splitProps(props,["class","value"]); const ctx=useContext(TabsContext); const active=()=>ctx?.value()===l.value; return <button type="button" role="tab" aria-selected={active()} data-slot="tabs-trigger" data-active={active()?"":undefined} class={cn("relative inline-flex items-center justify-center gap-1.5 whitespace-nowrap border-transparent px-1 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/35 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 data-active:text-foreground dark:hover:text-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 group-data-horizontal/tabs:-mb-px group-data-horizontal/tabs:h-10 group-data-horizontal/tabs:border-b-2 group-data-horizontal/tabs:data-active:border-primary group-data-vertical/tabs:w-full group-data-vertical/tabs:justify-start group-data-vertical/tabs:border-r-2 group-data-vertical/tabs:border-b-0 group-data-vertical/tabs:px-3 group-data-vertical/tabs:py-2 group-data-vertical/tabs:data-active:border-primary group-data-[variant=segmented]/tabs-list:-mb-0 group-data-[variant=segmented]/tabs-list:h-8 group-data-[variant=segmented]/tabs-list:rounded-full group-data-[variant=segmented]/tabs-list:border group-data-[variant=segmented]/tabs-list:border-transparent group-data-[variant=segmented]/tabs-list:px-3 group-data-[variant=segmented]/tabs-list:data-active:border-primary group-data-[variant=segmented]/tabs-list:data-active:bg-primary/10 group-data-[variant=segmented]/tabs-list:data-active:text-primary",l.class)} onClick={() => ctx?.setValue(l.value)} {...r}/> }
function TabsContent(props: JSX.HTMLAttributes<HTMLDivElement> & { value: string }) { const [l,r]=splitProps(props,["class","value"]); const ctx=useContext(TabsContext); return <div role="tabpanel" data-slot="tabs-content" hidden={ctx?.value() !== l.value} class={cn("flex-1 pt-4 outline-none",l.class)} {...r}/> }
export { Tabs, TabsList, TabsTrigger, TabsContent, tabsListVariants }
